server:
  port: 8896

spring:
  application:
    name: springboot-profile
  profiles:
    active: local
  main:
    banner-mode: off
  datasource:
    hikari:
      max-lifetime: 0

  redis:
    timeout: 10000
    lettuce:
      pool:
        max-active: 1000
        max-idle: 10
        min-idle: 3
        max-wait: -1


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  mapper-locations: classpath:mybatis/*/*Mapper.xml
  type-aliases-package: com.deuteriun.*.mapper
  global-config:
    banner: false

swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: Deuteriun API

logging:
  config: src/main/resources/logback-prod.xml

deuteriun:
  redis:
    #    min
    timeout: 10
  http-permitall-address-list:
    - /swagger-ui/**
    - /swagger-resources/**
    - /v3/**
    - /csrf
    - /login/**

  jwt-secret-key: changethiskey
  #  min
  jwt-expire-time: 4320
  #  min
  jwt-refresh-expire-time: 5


