package com.deuteriun.system.dao;

import com.deuteriun.system.entity.SysRole;

import java.util.List;

public interface SysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Mon Mar 14 01:49:01 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Mon Mar 14 01:49:01 CST 2022
     */
    int insert(SysRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Mon Mar 14 01:49:01 CST 2022
     */
    int insertSelective(SysRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Mon Mar 14 01:49:01 CST 2022
     */
    SysRole selectByPrimaryKey(Integer id);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Mon Mar 14 01:49:01 CST 2022
     */
    int updateByPrimaryKeySelective(SysRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Mon Mar 14 01:49:01 CST 2022
     */
    int updateByPrimaryKey(SysRole row);
}