package com.deuteriun.system.dao;

import com.deuteriun.system.entity.SysUserRole;
import com.deuteriun.system.entity.SysUserRoleDetail;

import java.util.List;

public interface SysUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Mon Mar 14 01:49:01 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Mon Mar 14 01:49:01 CST 2022
     */
    int insert(SysUserRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Mon Mar 14 01:49:01 CST 2022
     */
    int insertSelective(SysUserRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Mon Mar 14 01:49:01 CST 2022
     */
    SysUserRole selectByPrimaryKey(Long id);

    List<SysUserRoleDetail> listAllByUserId(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Mon Mar 14 01:49:01 CST 2022
     */
    int updateByPrimaryKeySelective(SysUserRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Mon Mar 14 01:49:01 CST 2022
     */
    int updateByPrimaryKey(SysUserRole row);
}