package com.deuteriun.system.entity;

import java.util.Date;
import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class SysLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.id
     *
     * @mbg.generated Mon Mar 14 01:49:01 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.sys_user_id
     *
     * @mbg.generated Mon Mar 14 01:49:01 CST 2022
     */
    private Long sysUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.event
     *
     * @mbg.generated Mon Mar 14 01:49:01 CST 2022
     */
    private String event;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.event_id
     *
     * @mbg.generated Mon Mar 14 01:49:01 CST 2022
     */
    private Date eventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.level
     *
     * @mbg.generated Mon Mar 14 01:49:01 CST 2022
     */
    private Boolean level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.ip
     *
     * @mbg.generated Mon Mar 14 01:49:01 CST 2022
     */
    private Boolean ip;
}